name: i_rich_2
description: A new Flutter project.
#yaml codes
#remember indentation jst likepython
publish_to:
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - images/diamond.png
    - images/         #add all the images