// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRDFj63l0ry7R6V0hzBJb3S6nywBVhymo',
    appId: '1:1088324159787:web:4bf4ae71fec89d510b9d6e',
    messagingSenderId: '1088324159787',
    projectId: 'musically-8e00f',
    authDomain: 'musically-8e00f.firebaseapp.com',
    storageBucket: 'musically-8e00f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCCAuuFINFguNTZ0nhFCVad7GQgCVz6LA',
    appId: '1:1088324159787:android:1438a01f0d1f85d60b9d6e',
    messagingSenderId: '1088324159787',
    projectId: 'musically-8e00f',
    storageBucket: 'musically-8e00f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC59PqAjbWCIbBkEeusVCcg7mZwQ_dF910',
    appId: '1:1088324159787:ios:ab1e470e88e735840b9d6e',
    messagingSenderId: '1088324159787',
    projectId: 'musically-8e00f',
    storageBucket: 'musically-8e00f.appspot.com',
    iosBundleId: 'com.example.musically',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC59PqAjbWCIbBkEeusVCcg7mZwQ_dF910',
    appId: '1:1088324159787:ios:8248e6c6b25fd5e80b9d6e',
    messagingSenderId: '1088324159787',
    projectId: 'musically-8e00f',
    storageBucket: 'musically-8e00f.appspot.com',
    iosBundleId: 'com.example.musically.RunnerTests',
  );
}
